### ISSUE TITLE
Evaluate

### ISSUE THREAD

**Issue by Cluoyao** [louis-she/center-loss.pytorch#6]
Hi, thanks for your work, i want to ask you a question, how to do the test? I tested the resnet50 and epoch_100.pth.tar on lfw, with crop face, but the accuracy is 0.66. How can I reproduce this result? thank you.

**Comment by futureisatyourhand** [comment]
> Hi, thanks for your work, i want to ask you a question, how to do the test? I tested the resnet50 and epoch_100.pth.tar on lfw, with crop face, but the accuracy is 0.66. How can I reproduce this result? thank you.

hello,excuse me how to improve the accuracy for Center. I experiment Center applying OCR.
Thanks
